### ISSUE TITLE
"license" info is incomplete & outdated

### ISSUE THREAD

**Issue by djboersma** [OpenGATE/Gate#128]
The license directory contains the GPL and LGPL texts, but the LICENSE.txt file which should specify which source code is covered by which of these licenses only mentions "ClearPET LMF" libraries, followed by a directory paths from which it is not clear what code is actually meant by that. Naively reading this file I would conclude that most/all of our code is not covered by any license at all.

The CREDITS.txt file is out of date. For instance, Uppsala is missing from the list of institutions, I am missing from the list of code contributors, and the spokesperson info has not been updated.

**Comment by djboersma** [comment]
Note that Geant4 is **not** (L)GPL. It has its own "geant4 software license". I have not yet checked if it is similar to any of the more familiar open source / free software licenses (GPL, BSD, Apache, MIT, etc). And IANAL at all, so I have no clue what would be the best choice for us. But it seems urgent to resolve this now *before* we run into an actual legal "use case".

**Comment by Supernabla** [comment]
**Just to keep the conversation going**

I think, at the moment there are two dependencies which enforce GATE to adopt a GPL license for the distribution of its sources:

1. Mandatory: GATE links **statically** to CLHEP (GPL) and contains source code of CLHEP (GPL).
2. Optionally: GATE links **statically** to LMF (GPL).

On the other hand, the dynamic linking to ROOT (LGPL) and the use of ITK/RTK (Apache 2.0) is permissive, i.e. doesn't require the GATE sources to have a specific license. Moreover, both LGPL and Apache 2.0 are [GPL-compatible](https://www.gnu.org/licenses/license-list.en.html).

Concerning `LICENSE.txt`, here is a good example of how other software developer explain the licensing of their dependencies: [FFmpeg](https://github.com/FFmpeg/FFmpeg/blob/master/LICENSE.md).

Concerning the dependence on Geant4: Should the "Geant4 Software License" be incompatible with the GPL, it would forbid the binary distribution of GATE. I'm not sure whether it would clash with a source-only distribution of GATE. But after all it's GATE's main dependency...

In any case, distributing the GATE's sources under a LGPL license doesn't make sense to me, since a GATE installation does not produce any shared libraries for others to link to.

**Comment by dsarrut** [comment]
Done f057de5390db52818f1eaea516165e183a410f96
