### ISSUE TITLE
Geant4 MT version with Gate

### ISSUE THREAD

**Issue by pallav28** [OpenGATE/Gate#136]
Can anyone share insights on Gate's compatibility with Geant4 MT? Anyone planning or currently working on that? Is it really possible?  
By far I could understand that GateRunManager is needed to be changed so that G4MTRunManager and G4MTWorkerRunManager can be managed to run with shared and thread local objects. Is really possible to accumulate events initially and then individual threads can work on that?

**Comment by djboersma** [comment]
Short answer: we would love have MT GATE to but it's going to take a lot of coding to make it work correctly. See this recent thread on gate-users: http://lists.opengatecollaboration.org/pipermail/gate-users/2017-June/009738.html and the discussion in an old (and closed) issue #53. But maybe we are too pessimistic? You are very welcome to try to make a MT fork of GATE. You could get in contact with @BishopWolf , he already started on this.

**Comment by BishopWolf** [comment]
Currently you can view my work [here](https://github.com/BishopWolf/Gate). Basically it already started the G4MTRunManager, but Gate has a concept of a static initialization of the world which makes incompatible the MT schema. Moreover most of actors and geometries are built in a static way. Much shall change in Gate before we can move to MT.

**Comment by pallav28** [comment]
@BishopWolf Thanks your comment on this.  Could you please give a short description of the static initialization in Gate which is not compatible with MT version. What could be the possible change in Gate to make this happen?

**Comment by BishopWolf** [comment]
Actually the short version is too long to resume here. But a short resume of a resume is for instance
1. A bunch of `GateMessageManager* theGateMessageManager = GateMessageManager::GetInstance();` which implies a static construction of the object GateMessageManager in this case.
2. A bunch of `#define theMaterialDatabase GateDetectorConstruction::GetGateDetectorConstruction()->mMaterialDatabase` which are used afterwards in a lot of places
3. A bunch of calls to static objects like `GateARFSD* ARFSD = GateDetectorConstruction::GetGateDetectorConstruction()->GetARFSD();`
Another bunch of etceteras but the result is that when you call `/gate/run/initialize` everything seems ok and then `/gate/application/start` it starts the threads but soon you see a message as the world is not an instance of ParallelWorld and does not have the virtual methods implemented. This is just the peak of the iceberg.

**Comment by Supernabla** [comment]
> [...] as the world is not an instance of ParallelWorld and does not have the virtual methods implemented.

Can you elaborate on that? I'm a bit confused about the term `ParallelWorld` in that context.

Geant4's concept of [parallel worlds](https://geant4.web.cern.ch/geant4/UserDocumentation/UsersGuides/ForApplicationDeveloper/html/ch04s07.html) is aimed towards the navigator, in order to decouple read-out geometries from the *mass geometry* a particle is transported in. (...)

However, `ParallelWorld` is not a term related to multi-threaded Geant4 and was introduced long before (Geant4 8.2.). GATE does not need parallel worlds to use the `G4MTRunManager`.

**Comment by BishopWolf** [comment]
@Supernabla Sorry for this delayed answer, I am really out of time. I just explained what Gate tells in the exception, I had not the time to go further since I dedicated a lot to try to put it like geant4 says it was ok but then I couldn't handle that error since I am like you annoyed by that message. Maybe is something to do with unsafe operation or something else. As I said it is just the peak of the iceberg.
