### ISSUE TITLE
can't run /benchmarks/benchImageNavigators/pet 

### ISSUE THREAD

**Issue by gsize** [OpenGATE/Gate#137]
In VGate, when I  run the example in   benchmarks/benchImageNavigators/pet ,there was one error.
the same in  Gate_v8.0.

GateSourceVoxelInterfileReader::ReadFile : fileName: data/brain_phantom.h33
 Header read from       'data/brain_phantom.h33'
 Data file name         'brain_phantom.i33'
 Nb of planes:           16
 Nb of pixels per plane: 32 32
 Pixel size:             8.800e+00 8.800e+00
 Slice thickness:        1.120e+01
 Matrix size:            2.816e+02 2.816e+02
 Data type:              UNSIGNED INTEGER
 Bytes per pixel:        2
 Data byte order:        LITTLEENDIAN
 Machine byte order:     LITTLEENDIAN

GateMiscFunctions.cc (l.88): Error while opening brain_phantom.i33 for reading.

 *** Break *** segmentation violation

**Comment by Milan991** [comment]
How did you solved this issue? I've similar issue:

`GateMiscFunctions.cc (l.99): Error while opening output/stat.txt for writing.`

**Comment by djboersma** [comment]
As the name indicates, there are "miscellaneous functions" in `GateMiscFunctions.cc`, and it looks to me that these errors are different, with different causes. The original issue was a problem with opening a file for _reading_; it looks like an input file did not exist, and Gate should then emit an error message and terminate normally, but it stumbled into a segfault, embarrassingly. Your issue is one with opening a file for _writing_ (two different functions in `GateMiscFunctions.cc`). Did you also get a "segmentation violation"?
One possible trivial cause for your error is if you run Gate in a directory that does not yet have an `output` subdirectory. Creating that subdirectory should fix the issue. Other possibilities are that the disk is full, or that you start Gate in a directory in which you do not have writing permissions for some reason.

**Comment by Milan991** [comment]
@djboersma Thank you. I've put full paths to the output files and everything works fine now.
