### ISSUE TITLE
Incompatibility between the crystalSD and phase-space files

### ISSUE THREAD

**Issue by miriam-mc** [OpenGATE/Gate#340]
Hello,

To try and answer the question of whether such an incompatibility exists I am measuring projection data due to a spherical (large ‘point’) 140 keV source  with a crystalSD sensitive detector and dose to water in a cube of water (both are at different points in space) and the latter is really only there as an independent test of the phase-space file.

If the spherical source is a GPS defined source then the detector produces expected projection data (a circle) and I get an amount of dose deposited in the cube of water.  The issue is that if I collect a phase space file for the same spherical source and then run a second simulation using this phase space file in lieu of the gps, I get the same amount of dose measured in my cube of water but I get no projection data in the sensitive detector.

Is there any reason why the sensitive detector (I am digitizing the results with the digitizer to simulate a spect gamma camera as per the SPECT example provided) should not recognise and therefore count the photons from the phase space file.  I have been investigating this for well over a week and each test I do (this is the simplest) suggests my phase-space source is perfectly fine – but the crystalSD detector is not measuring it.

I assume a photon is a photon regardless of its source in GATE – and I am starting to convince myself there must be a bug somewhere.  Has anybody successfully used a phase space file with this sensitive detector??

Any advice on how to go about digging into the code if there is a bug would be most appreciated.

Cheers,
Miriam

**Comment by miriam-mc** [comment]
**Further Testing:**
Investigating this problem further, I employed the use of the EnergySpectrumActor and the ParticleInVolumeActor. I ran the simulation four times, each time placing the source inside the same volume, with a SPECThead detector in place. First, using the point source described above, collecting the dose and number of particle data in the volume of water on the opposite side of the source from the detector. Second, the same set up but with the Phase space file of the point source. Third, back to the point source, with the actors now attached to the crystal volume within the SPEACThead. And finally, the phase space source with actors attached to the crystal volume. 

**Observations:**
When the dose actor is attached to the crystal volume, no projection data is collected for the point source. When the dose actor is not attached to the crystal volume, the projection data for the point source is clear. 
The energy spectrum across each of the four simulations followed the same pattern. The probability values were slightly different between them, which is expected, but they all clearly showed a peak around 140 keV and no energy higher than 144 keV, as expected for a 140 keV source.
The image for the number of particles entering the volume, when the actor is attached to the crystal volume, shows the same image (allowing for a different random seed) whether the point source or phase space source is in use. 

**Current Conclusions:** 
This test shows the phase space file does have photons being produced, and that they do interact in the crystal. However, no projection data is produced for the phase space file. This indicates the problem is somewhere between the phase space photons interacting in the crystal, and the system registering them as valid projection data, despite the energy spectrum data showing they have the same range of energies as the point source.

**Comment by dsarrut** [comment]
Hello, thanks a lot for the detailed report! I don't have time atm to investigate myself, but this is an important point. I will try to see if other people can handle it. Thanks for your patience!

**Comment by anetxe** [comment]
Thank you very much Miriam. 
In fact, there is no such incompatibility between crystalSD and phaseSpace source. The described issue is due to the difference in the time distribution of the simulated photons when the different sources were employed (gps and phaseSpace source).

By default, time information is not stored in the phaseSpace file. There was no time information stored in the employed phaseSpace input file. When this file was selected as a source, simulated photons were distributed in a few nanoseconds, whereas when gps source was employed photons were uniformly distributed in 1 s. In this example, a 2 us dead-time module was applied to singles in the digitization chain. Therefore, when phaseSpace source was employed only the first single was accepted and recorded in the projection output file. The lack of data in the projection output file was due to the combination of the time distribution of the simulated photons and the applied dead-time module.

By default, time information is not stored in the phaseSpace file. It is important to enable it when the results depend on the time distribution of the simulated photons.

/gate/actor/[actorName]/enableTime true
