### ISSUE TITLE
Generic Repeater for SPECT study - Received a hit with a wrong head ID...

### ISSUE THREAD

**Issue by smarshnz** [OpenGATE/Gate#347]
Hi
I am simulating a multi-head SPECT system in Gate 9.0. I use the SPECThead/repeaters/insert macro to make multiple heads.

If I use /gate/SPECThead/repeaters/insert ring  then all works - by works I mean I can visualise multiple heads and I collect projection data for each head separated in the output file.  The problem I wish to bring up here arises when I use the generic repeater option i.e. gate/SPECThead/repeaters/insert genericRepeater

As per before, the simulation visualises correctly - however I get an issue at the end of the simulation whereby data are not written as expected to the output file.  I also get the following message: 
[GateToProjectionSet::Fill]:
Received a hit with a wrong head ID (1): ignored!
[GateToProjectionSet::Fill]:
Received a hit with a wrong head ID (1): ignored!

The above is for a two-head system. I am trying to run a four head unevenly-spaced camera but the above highlights the issue.

Any help much appreciated.

**Comment by miriam-mc** [comment]
Hi,
I have the same experience when using the genericRepeater with a four head SPECT system. 
I set up the genericRepeater with:
/gate/SPECThead/repeaters/insert                       genericRepeater
/gate/SPECThead/genericRepeater/setPlacementsFilename  data/SPECThead.placements
/gate/SPECThead/genericRepeater/useRelativeTranslation 1

The SPECThead.placements looks like this:
Time     s
Rotation deg
Translation cm
0	180 	 0 1 0 	 0  0 49.99
0	256.0 	 0 1 0 	 -48.51  0 12.09
0	0 	 0 1 0 	 0  0 -49.99
0	76.0 	 0 1 0 	 48.51  0 -12.09

The visualization shows four SPECTheads spaced out as directed.
As the simulation runs I get the following error:
Received a hit with a wrong head ID (1): ignored!
[GateToProjectionSet::Fill]:
Received a hit with a wrong head ID (1): ignored!
[GateToProjectionSet::Fill]:
Received a hit with a wrong head ID (3): ignored!
[GateToProjectionSet::Fill]:
Received a hit with a wrong head ID (3): ignored!
[GateToProjectionSet::Fill]:
Received a hit with a wrong head ID (2): ignored!
[GateToProjectionSet::Fill]:
Received a hit with a wrong head ID (2): ignored!
[GateToProjectionSet::Fill]:
Received a hit with a wrong head ID (2): ignored!

And the projection data, after the simulation has finished, would be fine except it is only the data for one head. I presume it shows data for head 4 (or 0 if the head indices begin at 0 not 1) as that is the number not used in the error message.

I would also be very interested in any solution that this problem may have.

**Comment by anetxe** [comment]
The problem is that the number of total heads of the system is not correctly considered by GateToProjectionSet class when using a generic repeater. 

GateToProjectionSet::RecordBeginOfAcquisition()  loads  the number of heads by asking to the system how many copies of the head were built using the angular repeater (m_system->GetBaseComponent->GetAngularRepeatNumber();) If the angular repeater is not found the number of detector heads of the systems is set to 1. This is what happened when you employed a generic repeater. Then, in GateProjectionSet class, when filling the projections if the  headID is equal or higher than the number of detector heads those counts are not taken into account. So only the projection from  headId=0 is stored.
