### ISSUE TITLE
TPS pencil beam source

### ISSUE THREAD

**Issue by djboersma** [OpenGATE/Gate#73]
Another summer project: update `GateSourceTPSPencilBeam`.

(1) pencil beam initialization

Right now **all** pencil beams in a given plan are initialized at the start of the simulation as `GateSourcePencilBeam` objects. GSPB is not a simple struct, so for big treatment plans with many thousands of spots this takes a lot of RAM. In my current treatment case it's about 2GiB, Hermann told me that in he also saw Gate using 8 GiB due to `GateSourceTPSPencilBeam`. That is unpractical, for instance for simulating many (versions of) plans on a cluster. It would be better to have just a single GSPB object at any point in time. This would also model the reality much closer, where we treat with just a single pencil beam that has the same properties (it does not jump from proton to carbon, or from one set of source properties to another). 

(2) spot specification text file parsing

This is a different problem related to the same code: the text file parsing code is not very robust. The number of comment lines is hard-coded and if the user accidentally inserts or removes comment lines then the rest of the file yields bogus results or is ignored altogether, WITHOUT reporting any errors. This is in particular a problem for users who generate their spot file from non-DICOM input (because for dicom there is the `clitkDicomRTPlan2Gate` utility in `vv`). Minor mistakes can lead to a waste of a lot of time.

I would like to:
(a) allow arbitrary numbers of comment lines
(b) let each line start with a keyword, which may help to catch mistakes

Wish (a) is easy to implement: just replace all the `for (i=0; i<Nlines; i++) getline(buf);` expressions (where `Nline` is some hardcoded number) with a `GateReadLine` function which reads lines of text and returns the first non-empty non-comment line.

Wish (b) is also easy.

Of course there LOTs of other solutions (xml, dicom) but I like my solution because it is much less invasive while still addressing the problems I raise. The old format can still be supported (backwards compatibility), the new format can for instance be triggered by an obligatory keyword in the first comment line of the file (so that first comment line should of course *not* be skipped). And the `clitkDicomRTPlan2Gate` utility in `vv` could be updated to enable the new format (but as long as we keep the TPS code backwards compatible, that's not urgent).

(3) Convergence/divergence

Minor issue: a pencil beam can be convergent in X but divergent in Y and vice versa. At Skandion we see this at the lowest energy, `Ekin=60MeV`. For a single pencil beam source one can configure this, but in the TPS pencil beam source it's currently restricted to completely divergent or completely convergent. It would be nice to flexibilize this.

**Comment by dsarrut** [comment]
Hi David, 

very interesting points indeed !

- (1) right. I already recently modified a bit to avoid empty spot, it could save large amount of memory in some cases (c1cbf862539a406608751a323c19ed35875c7193). At some points I agree a single object should be created. 
- (2) 100% agree with your solution !
- (3) ok, to discuss with Loic. 

At some points, we should have a meeting to re-organize tools such as clitkDicomRTPlan2Gate, maybe to make them available in the source code of Gate (now it is easier because ITK can be linked with Gate). 

thanks, 
David

**Comment by brenthuisman** [comment]
@dsarrut: I recall removing empty controlpoints (and saving a nice chunk of memory). Is that code still there? I can't find it.

I have noticed the lack of robustness of the tps-plan parser also ;) If the on disk format changes, it won't be useful, but just in case it is of interest to anyone, here the parser I wrote (I wanted to plot the plans):
https://github.com/brenthuisman/phd_tools/blob/master/rtplan/__init__.py
I recall it does a little bit more bookkeeping than Gate does now. What would perhaps be simpler than changing the format, is checking the info already in the format (count the number of spots, layers and so on), for most things there's duplicate info. For comments, we could add a symbol (//) at the beginning of a line.

Perhaps it would be nice to have a contrib-repo, so that users have a place to put such things. There are more tools apart from clitkDicomRTPlan2Gate (clustertools, mergetools in particular) that should live closer to Gate than now.

What's not consistent either is terminology: layers vs controlpoints (mostly my doing I think).

**Comment by dsarrut** [comment]
Thanks Brent. 
Regarding empty controlpoints, it is now in the repo (maybe you did not commit your modifications ?). We are currently thinking on a way to include useful additional tools in the Gate repo. Regarding user contributions, nothing is planed now, but anyone could easily post some code on github and refer to everyone on the mailing list ...

**Comment by dsarrut** [comment]
I close it, considering the discussion #84
