### ISSUE TITLE
Compile issues due to implicit ROOT dependencies in 7.2

### ISSUE THREAD

**Issue by dfreese** [OpenGATE/Gate#76]
I ran into the same issue seen [here](http://comments.gmane.org/gmane.comp.science.opengate.user/4140), where I ran into the following errors when compiling with ROOT support disabled:

```
error: invalid use of incomplete type ‘class GateARFSD’
   if (arfSD->PrepareCreatorAttachment(this)) {
            ^
In file included from
/home/ayush/Downloads/gate_v7.0/source/geometry/src/GateVVolume.cc:29:0:
/home/ayush/Downloads/gate_v7.0/source/geometry/include/GateDetectorConstruction.hh:33:7:
error: forward declaration of ‘class GateARFSD’
 class GateARFSD;
       ^
/home/ayush/Downloads/gate_v7.0/source/geometry/src/GateVVolume.cc:639:23:
error: cannot convert ‘GateARFSD*’ to ‘G4VSensitiveDetector*’ in
assignment
   m_sensitiveDetector = arfSD;
```

It seems like there are still implicit ROOT dependencies that aren't guarded out.  There was a patch for this back then.  Wanted to check, is there a reason that patch hasn't been added?

**Comment by dsarrut** [comment]
Hello, 

to my knowledge, ROOT is now needed for Gate, there is no more cmake option to compile Gate without ROOT. 

David

**Comment by dfreese** [comment]
Ah okay.  The following in the [CMakeList.txt file](https://github.com/opengate/gate/blob/187b74f/CMakeLists.txt) and the [installation wiki](http://wiki.opengatecollaboration.org/index.php/Installation_Guide_V7.2) convolutes that issue a little bit.

```
# Option for Root use
SET(GATE_USE_ROOT ON)
SET(GATE_ANALYSIS_USE_GENERAL ON)
SET(GATE_ANALYSIS_USE_FILE ON)
```

**Comment by dsarrut** [comment]
exact, you're right ! I admit I never try to compile without root ... 
Could you retrieve the patch you mention ?

**Comment by dfreese** [comment]
The patch that I saw in the original message thread was found [here](https://dl.dropboxusercontent.com/u/43097994/gate7/root.patch.gz).  It looks like it was something done in the work towards v7.0.

Which would be the better option: getting the patch adjusted the current code, or removing the option of compiling without root?

**Comment by dsarrut** [comment]
thanks ... I don't know which one is better. On my side I may be tempted to remove the option of compiling without root, but I don't know if other people find it useful. 

The patch cannot be applied easily because the code change a bit since then ...

**Comment by patayg** [comment]
I was the author of the aforementioned patch. I tried to update it, but ROOT dependencies are now so uniformly scattered in the source code that I'd rather vote to simply drop the "compile without ROOT" option.

**Comment by dsarrut** [comment]
ok, let's do like that so: @patayg dont spend time to update the patch, eventually could you please instead remove the option to compile without root (and make a pull request) ?

**Comment by djboersma** [comment]
I guess I am a bit late to join the discussion, but I would like to mention that in my previous project (IceCube), we had a code base that is of similar scale as GATE, and in which we also were trying to use ROOT as a library. We ran into a couple of unpleasant surprises that made us decide to make the effort of enabling ROOT-free builds of our software. Basically we would have liked to use ROOT as a library, but ROOT thinks of itself as a framework that is in charge of everything, and it is doing many more things behind your back than you think (memory management, LOTS of global variables, access to home directory), even when all you are trying to do is to create a simple histogram and save it into a file.

So I would be in favor of keeping our GATE code base similarly defensive, and to try to support ROOT-free builds. On the other hand I understand that this involves quite a bit of extra work, at least on the short/medium term. On the long term it might actually save time (if my scaremongering turns out to be justified and relevant to GATE...).

If you like I could try to obtain a more specific list of ROOT trouble points from the IceCube software gurus, if that could help to decide how to act on this with GATE.

**Comment by patayg** [comment]
Actually, the "compile without ROOT" flag is removed from the CMake options since the commit 5fbb437, so it should not cast any problem for a 'regular' user.

Still, it would be a nice feature to have a ROOT-free build with fewer dependencies at the cost of limited functionality, e.g. no ARF modeling, lack of several actors and ROOT output.

**Comment by brenthuisman** [comment]
I think everyone agrees ROOT is not great but I've looked for alternative libraries that can write ROOT histograms and TTree and such and did not find any. Many actors do use ROOT classes, so removing it basically only leaves you with the various voxelized dose actors, wouldn't it? To me that sounds like a very limited version of Gate.

In Geant4 there is the `source/analysis/g4tools/include/tools` directory, where there are appears to be a minimum implementation of some of ROOTs classes minus the lovely framework features. Perhaps we can simply copy/link to that.

**Comment by dsarrut** [comment]
Gate needs ROOT
