### ISSUE TITLE
Bug in source intensity ? 

### ISSUE THREAD

**Issue by dsarrut** [OpenGATE/Gate#83]
Hello, 

when using a voxelised source with the "setIntensity" option, the intensity is not taken into account. 
Example:
```
/gate/source/addSource my_src voxel
/gate/source/my_src/reader/insert image
/gate/source/my_src/imageReader/translator/insert linear
/gate/source/my_src/imageReader/linearTranslator/setScale 1 MBq
/gate/source/my_src/imageReader/readFile data/my_src.mhd
/gate/source/my_src/gps/particle gamma
/gate/source/my_src/gps/monoenergy 100.0 keV
/gate/source/my_src/setIntensity 0.5
```

If a 1 second simulation is performed, instead of 0.5 million particles (I assume the sum of all voxels in the image is 1), we get 1 million. 

One solution (1) could be to replace the line https://github.com/OpenGATE/Gate/blob/develop/source/physics/src/GateSourceVoxellized.cc#L49
` G4double firstTime = GateVSource::GetNextTime(timeNow);`

with 

` G4double firstTime = GateVSource::GetNextTime(timeNow)/GetIntensity();`

But this would be specific to voxelized volume.

Another solution (2) could be line https://github.com/OpenGATE/Gate/blob/develop/source/physics/src/GateSourceMgr.cc#L341
by dividing the `aTime` according to the intensity. 

Yet another solution (3) in the function `GetNextTime` : https://github.com/OpenGATE/Gate/blob/develop/source/physics/src/GateVSource.cc#L258

Before I commit something (maybe solution 2), I would like some advices ... 

some ideas ?
David

**Comment by djboersma** [comment]
My 2 cents....

First cent: there does not seem to be any documentation at all in the source code about the intended role/purpose of the "set intensity" method and why it needs to be a feature at the `GateVSource` level. For instance `GateSourceTPSPencilBeam` is also a `GateVSource`, and I have no idea what the meaning of "set intensity" for that source should be. It seems something that is specific to brachyotherapy sources. But your source also let your set the scale to "1 MBq", so if I understand the expected effect of intensity=0.5 correctly then you should be able to achieve the same thing by setting the scale to 0.5 MBq and keeping the intensity at 1. Correct?

Second cent: if the "time" means "number of simulated seconds passed since beginning of the simulated treatment/imaging", then I do not understand your solution number (1). Suppose that you are halfway a 1 second simulation, so `timeNow` is 0.5 seconds with double intensity, so intensity=2. Then `GetNextTime` might return for instance 0.51 seconds, but after dividing by intensity you get 0.255 seconds. So the simulation goes back in time! I guess you mean to divide the time **difference** by the intensity. And where you would do this depends on the answer to my first "cent": does "intensity" indeed have a single well defined meaning for all available sources or should you specialize it to a particular category of sources?

**Comment by dsarrut** [comment]
First cent: yes right. 
Second cent: right also, it is the time diff that should be modified. 
But indeed, I do not know what is the intended global meaning of "intensity". So I think I will keep it without change and change my plan to alternative approach. 

Thanks for the comments !
