### ISSUE TITLE
How long will we keep C++11 optional?

### ISSUE THREAD

**Issue by djboersma** [OpenGATE/Gate#90]
I wonder when we should start requiring developers/users to compile  Gate with C++11. This "new" standard is now 5 years old, there is already a newer one (C++14) and in 2017 there will be yet another one. I am not necessarily advocating that we should jump to the bleeding edge, but I do think that at some point we should decide that we do not need to keep our code 2003-compatible anymore. All the tools that we depend on (geant4, root, ITK) have provided C++11 versions already long ago.

I think that the main argument for keeping the code 2003-compatible is to be nice to users with very old systems, running Ubuntu 12/04 or even 10/04. But I think/hope that those users are getting very rare, and maybe some of them can be gently encouraged to join the modern times with a shiny new linux distro.

On the other hand, if we do not want to repeat this discussion every 3 years (because on https://isocpp.org/std/status you can see that after 2017 the standards committee won't stop innovating) then some of us might even be tempted to leapfrog directly to c++2014. I am reading Scott Meyers' "Effective Modern C++" and I get the feeling that C++14 is kind of a "bugfix release", making many of the new elements in C++11 more convenient and consistent. But you can't compile C++14 code with gcc 4.8, which I think is still very popular.

I am opening this issue because I think that there needs to be a discussion and eventually a smart & practical policy/decision/agreement/compromise about our choice of C++ standard(s). I guess we can collect facts & opinions & things to consider, and then discuss it all in Strasbourg.

**Comment by mojca** [comment]
I believe that one can no longer install Geant4 without C++11. Please correct me if I'm wrong. I'm not sure which Geant4 version is still supported in Gate. While supporting pre-C++11 compilers and OSes that don't support C++11 (like OS X < 10.9) is nice in theory, I don't think that it brings any benefit if all the dependencies need C++11 anyway.

**Comment by brenthuisman** [comment]
It would be nice if there is an explicit target for compatibility. I do not use new C++ stuff in Gate for fear of being incompatible, but it would be very nice if we could! Since many here will use Gate on clusters with CentOS(-derived such as Cern Linux), perhaps the version of GCC in that distro is a good target. As per http://distrowatch.com/table.php?distribution=centos , CentOS 7 (latest) has GCC 4.8 and CentOS 6 has GCC 4.4.

**Comment by djboersma** [comment]
I just tried to compile geant4.10.2.p02 on a RHEL6 machine. It already balks the cmake version, 2.6.4, and demands version 3.3 or higher. That particular machine has a whole set of modern tools in parallel to the official system: modern cmake, clang version 3.8, etc. So yes it is possible to use modern geant4 on RHEL6/CentOS6, but users will have to install new build tools to override the outdated system versions. And if they do that for geant4, they can also use it for building Gate. Like @mojca already implied.

**Comment by brenthuisman** [comment]
Here our servers upgraded a while after Geant4/Gate already changed to CMAKE 3.3, which meant we had to use old versions for a while, which was not ideal. In general I would not assume people control development tools such as GCC or Cmake on their servers (or even locally), and then it's really nice if the project does not require the latest version of every tool it depends on. At my other lab we don't even control our own desktops, and they simply stick to Gate 6.x (maybe 7.0 by now, it still supported Geant4.9.6), which is really a pain.

On the other hand, being compatible with versions lower than required by Geant4 itself doesn't really help anyone, so I'd suggest that we make sure we can build Gate with the same versions that the lowest supported Geant4 version can be built with. So if we support down to [Geant4.10.0](http://geant4.cern.ch/support/ReleaseNotes4.10.0.html), we make sure we can build with GCC 4.4 (I think, not sure) and Cmake 2.8.12.

I know some people don't care because they don't encounter these problems, but I assure you PhD students often interact with older desktops/servers that they can't control ;)

**Comment by djboersma** [comment]
On the Gate 7.2 download page I see that for that release, geant4 10.2 was required, so 10.0 was too old apparently. I do not know how exactly this geant4 minimum version requirement is chosen/determined; could someone else maybe comment on that, is it related e.g. to the physics models?

I raised this issue with the development version in mind, I do not want to impose new requirements on the build system for the old releases. But if we required geant4 10.2 for the Gate 7.2 release, then I think it is safe/reasonable to assume the same requirement (or newer!) for the current development version and next release of Gate, with the corresponding requirements for the build system (including cmake and compiler).

**Comment by brenthuisman** [comment]
I think there currently there's no formally defined set of minimum versions, the Gate download page doesn't seem to distinguish required and recommended. I run the `develop` branch against Geant10.1 without problem. In Gates CMakeLists.txt:73 I see an explicit check for 10.1 and 10.2 (so 10.3 wouldn't work!). I bet if we remove the check 10.0 would work fine as well, because I think Geant4 doesn't change API between minor versions. (I suppose Geant4 support is not unit tested?)

Re: C++11 support, the release notes of Geant4 mention it first in 10.1, and in 10.2 it is default. Before 10.2, Linux with GCC 4.4 (Scientific Linux CERN 6) was the officially supported platform. With 10.2 it changed to Linux GCC 4.8 (CERN CentOS Linux 7).

Does `develop` now depend on specific 10.2 features? If not, I'd vote for keeping some backwards compatibility. In either case: yes sticking with the same requirements as the lowest version of Geant4 that Gate requires seems the logical choice.

**Comment by mojca** [comment]
C++11 is a strict requirement since Geant4.10.2 (and since ROOT 6). Many components of Qt 5 no longer compile without C++11 either.

When it starts being annoying to keep compatibility over multiple versions of Geant4, I find it more important to be compatible with the latest version of Geant4 than to try to keep compatibility with "ancient" versions of Geant4 at all costs. If anything, many people that urgently need the latest and greatest version of Gate would probably want a recent version of Geant4 as well.

I'm in charge of some packages for OS X and in a special way I "hate software" that switches to C++11 because that causes headaches for support on older Macs. But then again ... support for legacy systems shouldn't be holding the development back. If you can write better and more efficient code using C++11, do that. I would not consider it too bold of a move if Gate switched to C++11 given its dependencies switched quite a while ago already. Sure, it's nice to be friendly to users, just not at all costs.

**Comment by brenthuisman** [comment]
Latest version minus 0.1 is not ancient software ;) Practically speaking, there is C++11 code in Gate now, so we require a compiler that can compile Geant4 10.2 as well, so dropping support for earlier makes sense from that perspective. I suspect Geant4's requirements will remain stable for a while now (which seem in tandem with Cern CentOS releases). Based on that, keeping support for older Geant4 versions around is 'free' until the next major release.

I'm making the case for the cluster use case, which tend to run slightly outdated software, tend to be out of user control (and do not require Qt etc), and yet are used by people on `develop`. Keeping in mind that `develop` is the next point release, we can use features/dependencies accordingly.

In addition: I keep Geant4.10.1 around because of changes in physics lists. If you validate Geant4 against something, you probably do not like a narrow Geant4 support window either. I can imagine I'm not the only one not particularly interested in revalidation every point release.

**Comment by djboersma** [comment]
I'm sorry that I failed to put this "C++ standard" issue on the agenda for Strasbourg. Maybe I forgot about it because in the conversation here it looked like we converged on the idea that we should just go for C++11, make it required/non-optional, because it is also non-optional for the geant4 version that we require. But maybe only a few people actually read this discussion...

**Comment by dsarrut** [comment]
c++11 is non-optional for G4 ? In that case, I think we should make Gate default with c++11. We may keep the options for those interested to compile with other versions. I cannot find from which G4 version this is mandatory ?

**Comment by dsarrut** [comment]
Closed, because now c++11 is needed
